import {
  ArrowRight,
  BadgeCheck,
  Ban,
  Bell,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CirclePlay,
  CircleX,
  ClipboardList,
  Clock,
  CloudUpload,
  Compass,
  CreditCard,
  Crown,
  Ellipsis,
  ExternalLink,
  Factory,
  FileCheck,
  FileText,
  FolderOpen,
  Gem,
  HardDrive,
  Hammer,
  Hourglass,
  House,
  Image as ImageIcon,
  Images,
  IndianRupee,
  Info,
  Landmark,
  LandPlot,
  LayoutGrid,
  LifeBuoy,
  LocateFixed,
  Lock,
  LogOut,
  Mail,
  Map as MapIcon,
  MapPin,
  Maximize2,
  MessageCircle,
  Minimize2,
  Moon,
  Navigation,
  Paperclip,
  PartyPopper,
  Pencil,
  Phone,
  Play,
  Plus,
  Receipt,
  RefreshCw,
  Route,
  Ruler,
  Satellite,
  ScrollText,
  Search,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  SprayCan,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Tag,
  Trash2,
  TriangleAlert,
  User,
  Users,
  Video,
  Wallet,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';
import { colors } from '@/theme';

/**
 * The ONE icon set used across Propittu (Lucide: consistent 2px strokes,
 * rounded joins). Screens refer to icons by these semantic names, never to
 * a library directly, so the whole app stays visually coherent.
 */
const ICONS = {
  // navigation & actions
  add: Plus,
  back: ChevronLeft,
  close: X,
  check: Check,
  chevron: ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  arrow: ArrowRight,
  edit: Pencil,
  delete: Trash2,
  more: Ellipsis,
  search: Search,
  refresh: RefreshCw,
  external: ExternalLink,
  expand: Maximize2,
  collapse: Minimize2,
  upload: CloudUpload,
  attach: Paperclip,
  logout: LogOut,
  lock: Lock,

  // places & property
  home: House,
  apartment: Building2,
  building: Building,
  land: LandPlot,
  store: Store,
  factory: Factory,
  pin: MapPin,
  map: MapIcon,
  navigate: Navigation,
  directions: Route,
  locate: LocateFixed,
  compass: Compass,
  satellite: Satellite,
  area: Ruler,

  // files & media
  document: FileText,
  'document-check': FileCheck,
  deed: ScrollText,
  folder: FolderOpen,
  camera: Camera,
  image: ImageIcon,
  images: Images,
  video: Video,
  play: Play,
  'play-circle': CirclePlay,
  storage: HardDrive,

  // services
  services: Sparkles,
  sparkles: Sparkles,
  wrench: Wrench,
  hammer: Hammer,
  cleaning: SprayCan,
  government: Landmark,
  shield: Shield,
  'shield-check': ShieldCheck,
  requests: ClipboardList,
  chat: MessageCircle,
  grid: LayoutGrid,

  // time
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  clock: Clock,
  hourglass: Hourglass,
  morning: Sunrise,
  afternoon: Sun,
  evening: Sunset,
  night: Moon,

  // account, plan & money
  user: User,
  users: Users,
  staff: Briefcase,
  phone: Phone,
  mobile: Smartphone,
  mail: Mail,
  support: LifeBuoy,
  bell: Bell,
  plan: Crown,
  gem: Gem,
  bolt: Zap,
  card: CreditCard,
  wallet: Wallet,
  rupee: IndianRupee,
  receipt: Receipt,
  tag: Tag,
  verified: BadgeCheck,
  celebrate: PartyPopper,

  // status
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleAlert,
  info: Info,
  cancelled: CircleX,
  blocked: Ban,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  size = 20,
  color = colors.text,
  strokeWidth = 2,
}: {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const Component = ICONS[name];
  return <Component size={size} color={color} strokeWidth={strokeWidth} />;
}
