-- =====================================================================
-- Propittu MVP — Storage buckets and object policies
-- PRODUCT_SPEC.md §19, §21, §37
--
-- Both buckets are PRIVATE. Property documents are sale deeds and tax
-- receipts; nothing here is ever publicly readable. Access is only via
-- short-lived signed URLs issued by the API.
--
-- Object paths are generated by the API, never by the client (§37):
--     <user_id>/<property_id>/<uuid>.<ext>
--
-- The first path segment is the owner's user id, which is what lets the
-- policies below verify ownership. Because the API calls Storage with
-- the caller's own JWT, these policies are enforced on every upload
-- URL it signs, every download URL it signs and every delete it makes.
--
-- Size and MIME limits are set on the bucket itself — the one layer a
-- bug in the app or API cannot route around (§21).
-- =====================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('property-photos',    'property-photos',    false, 5242880,  array['image/jpeg', 'image/png']),
  ('property-documents', 'property-documents', false, 10485760, array['application/pdf', 'image/jpeg', 'image/png'])
on conflict (id) do update
set public             = excluded.public,
    file_size_limit    = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;


-- ---------------------------------------------------------------------
-- Owner-folder policies. One policy per verb so each is easy to audit.
-- ---------------------------------------------------------------------

create policy property_files_select_own on storage.objects
  for select to authenticated
  using (
    bucket_id in ('property-photos', 'property-documents')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy property_files_insert_own on storage.objects
  for insert to authenticated
  with check (
    bucket_id in ('property-photos', 'property-documents')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy property_files_update_own on storage.objects
  for update to authenticated
  using (
    bucket_id in ('property-photos', 'property-documents')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  )
  with check (
    bucket_id in ('property-photos', 'property-documents')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

create policy property_files_delete_own on storage.objects
  for delete to authenticated
  using (
    bucket_id in ('property-photos', 'property-documents')
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
